web:
  build: .
  command: gunicorn app:app -w 4 --bind=0.0.0.0:8000 --max-requests=2 --log-level=debug --log-file=- --access-logfile=- --error-logfile=-
  working_dir: /usr/src/app
  volumes:
    - .:/usr/src/app
  env_file:
    - env.ini
